-- Initial Identity schema.
-- Idempotent: an existing retail360 database already has these tables.
-- Do not edit this script after it has been applied. Add a new numbered script.

create table if not exists asp_net_roles (
    id text not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    is_deleted boolean not null,
    name character varying(256) null,
    normalized_name character varying(256) null,
    concurrency_stamp text null,
    constraint pk_asp_net_roles primary key (id)
);

create table if not exists asp_net_users (
    id text not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    is_deleted boolean not null,
    user_name character varying(256) null,
    normalized_user_name character varying(256) null,
    email character varying(256) null,
    normalized_email character varying(256) null,
    email_confirmed boolean not null,
    password_hash text null,
    security_stamp text null,
    concurrency_stamp text null,
    phone_number text null,
    phone_number_confirmed boolean not null,
    two_factor_enabled boolean not null,
    lockout_end timestamp with time zone null,
    lockout_enabled boolean not null,
    access_failed_count integer not null,
    constraint pk_asp_net_users primary key (id)
);

create table if not exists asp_net_role_claims (
    id integer generated by default as identity,
    role_id text not null,
    claim_type text null,
    claim_value text null,
    constraint pk_asp_net_role_claims primary key (id),
    constraint fk_asp_net_role_claims_asp_net_roles_role_id
        foreign key (role_id) references asp_net_roles (id) on delete cascade
);

create table if not exists asp_net_user_claims (
    id integer generated by default as identity,
    user_id text not null,
    claim_type text null,
    claim_value text null,
    constraint pk_asp_net_user_claims primary key (id),
    constraint fk_asp_net_user_claims_asp_net_users_user_id
        foreign key (user_id) references asp_net_users (id) on delete cascade
);

create table if not exists asp_net_user_logins (
    login_provider text not null,
    provider_key text not null,
    provider_display_name text null,
    user_id text not null,
    constraint pk_asp_net_user_logins primary key (login_provider, provider_key),
    constraint fk_asp_net_user_logins_asp_net_users_user_id
        foreign key (user_id) references asp_net_users (id) on delete cascade
);

create table if not exists asp_net_user_roles (
    user_id text not null,
    role_id text not null,
    constraint pk_asp_net_user_roles primary key (user_id, role_id),
    constraint fk_asp_net_user_roles_asp_net_roles_role_id
        foreign key (role_id) references asp_net_roles (id) on delete cascade,
    constraint fk_asp_net_user_roles_asp_net_users_user_id
        foreign key (user_id) references asp_net_users (id) on delete cascade
);

create table if not exists asp_net_user_tokens (
    user_id text not null,
    login_provider text not null,
    name text not null,
    value text null,
    constraint pk_asp_net_user_tokens primary key (user_id, login_provider, name),
    constraint fk_asp_net_user_tokens_asp_net_users_user_id
        foreign key (user_id) references asp_net_users (id) on delete cascade
);

create unique index if not exists role_name_index on asp_net_roles (normalized_name);
create index if not exists ix_asp_net_role_claims_role_id on asp_net_role_claims (role_id);
create index if not exists ix_asp_net_user_claims_user_id on asp_net_user_claims (user_id);
create index if not exists ix_asp_net_user_logins_user_id on asp_net_user_logins (user_id);
create index if not exists ix_asp_net_user_roles_role_id on asp_net_user_roles (role_id);
create index if not exists email_index on asp_net_users (normalized_email);
create unique index if not exists user_name_index on asp_net_users (normalized_user_name);

-- Names match Retail360.Domain.Identity.ShopRoleNames.
insert into asp_net_roles (id, concurrency_stamp, created_at, is_deleted, name, normalized_name, updated_at)
values
    ('8f4c2e1a-6b3d-4a91-9c70-1a2b3c4d5e01', '8f4c2e1a-6b3d-4a91-9c70-1a2b3c4d5e01', timestamptz '2026-10-06 00:00:00+00', false, 'Admin', 'ADMIN', timestamptz '2026-10-06 00:00:00+00'),
    ('8f4c2e1a-6b3d-4a91-9c70-1a2b3c4d5e02', '8f4c2e1a-6b3d-4a91-9c70-1a2b3c4d5e02', timestamptz '2026-10-06 00:00:00+00', false, 'Manager', 'MANAGER', timestamptz '2026-10-06 00:00:00+00'),
    ('8f4c2e1a-6b3d-4a91-9c70-1a2b3c4d5e03', '8f4c2e1a-6b3d-4a91-9c70-1a2b3c4d5e03', timestamptz '2026-10-06 00:00:00+00', false, 'Cashier', 'CASHIER', timestamptz '2026-10-06 00:00:00+00'),
    ('8f4c2e1a-6b3d-4a91-9c70-1a2b3c4d5e04', '8f4c2e1a-6b3d-4a91-9c70-1a2b3c4d5e04', timestamptz '2026-10-06 00:00:00+00', false, 'Inventory Staff', 'INVENTORY STAFF', timestamptz '2026-10-06 00:00:00+00')
on conflict (id) do nothing;
